# Generated by Django 5.1 on 2024-10-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chatroom_message_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
